### PR TITLE
Docker rootless support

### PR DESCRIPTION
**Pull request by pathros**
I added support for Docker Rootless.

This has been possible by adding the possibility to bind the docker.sock to the user's current $XDG_RUNTIME_DIR, which is found in the user's .bashrc file, that he added after installing docker rootless, by following the instructions from the official documentation (https://docs.docker.com/engine/security/rootless/) to run the Docker Daemon as a non-root user.

I have tested this already on an Ubuntu 20.04.2 VPS where I set up Docker rootless according to [the Docker rootless official documentation](https://docs.docker.com/engine/security/rootless/).

### CODE REVIEW

**Comment by evertramos** [comment]
I will need to test it in order to merge this PR and might take a while on that. but thanks in advance.

**Comment by evertramos** [comment]
Kind of late but could update the other related scripts into this PR. thanks again! nice job!!

**Comment by bjorn** [comment]
While trying to set up the latest version on a standard DigitalOcean docker-compose image, I was running into the following error when running `fresh-start.sh`:
```
✘ ERROR   You must inform the required argument(s) to the function: 'env_update_variable' 
   Replace string: DOCKER_HOST_ROOTLESS_PATH
```
Not knowing how to resolve that, I was able to get things set up by checking out the `v0.6` tag first. So, possibly the instructions need some kind of update after this change?

**Comment by pathros** [comment]
Also try running the help flag, so you can see all options available, and some explanation:

```bash
$ ./fresh-start.sh --help
```

**Comment by evertramos** [comment]
@bjorn 

We miss the optional update script when updating the env variable, I just fixed that. So please try again *without* the rootless option:

https://github.com/evertramos/nginx-proxy-automation/commit/3953465fe3c588a2ebcdb6cfd59b358ddd6721bc

**Comment by bjorn** [comment]
> Would you mind to try again and give us a feedback?

Well, I got my proxy working with `v0.6` and don't really want to run the setup script again for now. The fix looks good though, thanks!

**Pull request merged**
