### PR TITLE
README add Debugging Failed Connections

### PR DESCRIPTION
**Pull request by glanham-jr**
I had some issues with debugging a failed connection test, so I decided to place some of my debug steps here along with some additional good information. Feel free to request any changes to the doc if it isn't clear or misleading.

### CODE REVIEW

**Comment by evertramos** [comment]
Hello @glanham-jr, thanks for your suggestion. I wonder why do you use port 9000 with this repo? this should open only 80 and 443 and if you have dynamic dns this might but for home usage or testing. If you want to open a new HOWTO-server-at-home.md file feel free, as we have [HOWTO-Synology](https://github.com/evertramos/nginx-proxy-automation/blob/main/docs/HOWTO-Synology.md).

**Comment by glanham-jr** [comment]
Hi there -, so the example port of 9000 is used for debugging the current docker setup without this repo to ensure there are no other issues present in accessing containers. Pretty much its going through to make sure the user has setup their docker / server / routing correctly. And yes, this quick testing guide was for home usage and testing, which was my use case.

**Comment by evertramos** [comment]
will you create a new howto? or should I close this PR?

**Comment by glanham-jr** [comment]
@evertramos apologies for the delay - updated the docs and moved it to its own file.

**Comment by evertramos** [comment]
I will merge this PR, you can open a new one if you want to improve the docs. Thanks again

**Pull request merged**
